// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/pricing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_proto_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *QuoteRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QuoteRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	UnitPriceUsd  float64                `protobuf:"fixed64,2,opt,name=unit_price_usd,json=unitPriceUsd,proto3" json:"unit_price_usd,omitempty"`
	TotalPriceUsd float64                `protobuf:"fixed64,3,opt,name=total_price_usd,json=totalPriceUsd,proto3" json:"total_price_usd,omitempty"`
	AlgorithmId   string                 `protobuf:"bytes,4,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"` // identifies the pricing algorithm used; used to detect divergence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_proto_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *QuoteResponse) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *QuoteResponse) GetUnitPriceUsd() float64 {
	if x != nil {
		return x.UnitPriceUsd
	}
	return 0
}

func (x *QuoteResponse) GetTotalPriceUsd() float64 {
	if x != nil {
		return x.TotalPriceUsd
	}
	return 0
}

func (x *QuoteResponse) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

var File_proto_pricing_proto protoreflect.FileDescriptor

const file_proto_pricing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/pricing.proto\x12\x0emesh.shadow.v1\"Y\n" +
	"\fQuoteRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x92\x01\n" +
	"\rQuoteResponse\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12$\n" +
	"\x0eunit_price_usd\x18\x02 \x01(\x01R\funitPriceUsd\x12&\n" +
	"\x0ftotal_price_usd\x18\x03 \x01(\x01R\rtotalPriceUsd\x12!\n" +
	"\falgorithm_id\x18\x04 \x01(\tR\valgorithmId2V\n" +
	"\x0ePricingService\x12D\n" +
	"\x05Quote\x12\x1c.mesh.shadow.v1.QuoteRequest\x1a\x1d.mesh.shadow.v1.QuoteResponseB6Z4github.com/mizcausevic-dev/grpc-mesh-shadow/proto;pbb\x06proto3"

var (
	file_proto_pricing_proto_rawDescOnce sync.Once
	file_proto_pricing_proto_rawDescData []byte
)

func file_proto_pricing_proto_rawDescGZIP() []byte {
	file_proto_pricing_proto_rawDescOnce.Do(func() {
		file_proto_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pricing_proto_rawDesc), len(file_proto_pricing_proto_rawDesc)))
	})
	return file_proto_pricing_proto_rawDescData
}

var file_proto_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pricing_proto_goTypes = []any{
	(*QuoteRequest)(nil),  // 0: mesh.shadow.v1.QuoteRequest
	(*QuoteResponse)(nil), // 1: mesh.shadow.v1.QuoteResponse
}
var file_proto_pricing_proto_depIdxs = []int32{
	0, // 0: mesh.shadow.v1.PricingService.Quote:input_type -> mesh.shadow.v1.QuoteRequest
	1, // 1: mesh.shadow.v1.PricingService.Quote:output_type -> mesh.shadow.v1.QuoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pricing_proto_init() }
func file_proto_pricing_proto_init() {
	if File_proto_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pricing_proto_rawDesc), len(file_proto_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pricing_proto_goTypes,
		DependencyIndexes: file_proto_pricing_proto_depIdxs,
		MessageInfos:      file_proto_pricing_proto_msgTypes,
	}.Build()
	File_proto_pricing_proto = out.File
	file_proto_pricing_proto_goTypes = nil
	file_proto_pricing_proto_depIdxs = nil
}
